# Generated by Django 3.0.7 on 2020-06-27 13:57

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(auto_created=True, default='null', max_length=99999)),
                ('uid', models.IntegerField(default=login.models.User.number)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('mobile_number', models.CharField(max_length=15)),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
            ],
        ),
    ]
